### ISSUE TITLE
[Network] Max message size is limited to ~125kB.

### ISSUE THREAD

**Issue by HaySayCheese** [GEO-Protocol/GEO-network-client#11]
At the the moment, `Packet.hpp` defines network packet header in the next way:

```c++
    typedef uint16_t PacketSize;
    typedef uint32_t ChannelIndex;

    // Note: one message may contains no more than 2**8 = 256 packets.
    // Max message size depends on max packet size:
    // for the public network (Internet transfer) the appropriate packet size is 508 bytes.
    // Packet header may contains 8 bytes. As the result, data segment of the packet may contains 500 byte.
    // The max message size = ~125kB.
    typedef uint8_t TotalPacketsCount;
    typedef TotalPacketsCount PacketIndex;
```

`TotalPacketsCount` must be increased to support larger messages, otherwise - transactions in the system would be heavily constrained in participants count.

**Comment by minyor** [comment]
Increased TotalPacketsCount type from uint8_t to uint16_t.
Fixed algorithm for division transmitted data by packets.
Commit: 3b936842ac7b0ac92c35da609534e8797ca13f6a
